### ISSUE TITLE
where is the file wider_att_train_imglist.txt?

### ISSUE THREAD

**Issue by mensaochun** [cvcode18/imbalanced_learning#2]
Do I need to generate it myself?

**Comment by nsarafianos** [comment]
You can find it [here](https://github.com/zhufengx/SRN_multilabel) and to split it in train/val/test check [here](https://github.com/zhufengx/SRN_multilabel/issues/9)

**Comment by mensaochun** [comment]
> You can find it [here](https://github.com/zhufengx/SRN_multilabel) and to split it in train/val/test check [here](https://github.com/zhufengx/SRN_multilabel/issues/9)

Thank you.

**Comment by valencebond** [comment]
@nsarafianos @mensaochun  can you provide the txt file, i can not find it in origin repo. thanks~
