### ISSUE TITLE
saved model

### ISSUE THREAD

**Issue by mmchen88** [cvcode18/imbalanced_learning#4]
can you share your pretrained backbone model?

**Comment by usernoproblem** [comment]
same problem, please.

**Comment by cute-walk** [comment]
> can you share your pretrained backbone model?

Do you have a pre-trained backbone model now?
thank you very much

**Comment by AgnesLily** [comment]
> > can you share your pretrained backbone model?
> 
> Do you have a pre-trained backbone model now?
> thank you very much

do you have the pre-trained model now? thank you very much!

**Comment by summer1030** [comment]
> can you share your pretrained backbone model?

Thanks for opening the code. Can you share the pre-trained backbone model? Many thanks!

**Comment by VuNguyen597** [comment]
Sorry for the late response. I do not have  a pre-trained backbone model

**Comment by VuNguyen597** [comment]
Sorry for the late response. I do not have  a pre-trained backbone model

**Comment by VuNguyen597** [comment]
Sorry for the late response. I do not have  a pre-trained backbone model
