### ISSUE TITLE
data conversion

### ISSUE THREAD

**Issue by sbharadwajj** [cvcode18/imbalanced_learning#6]
Hi,

in `preprocessing.py`, I'm getting the following error.
```
L.append([str(c)]+map(str,tmp)+[str(im)])
TypeError: can only concatenate list (not "map") to list
```
I am new to mxnet and I am unable to convert using:
```
cd /incubator-mxnet/tools/
python im2rec.py /project/path/DeepVisualAttributes /dataset/path/WIDER --quality=100 --pack-label=True
```
As I dont know the format to which it needs to be converted, as in the exact format the `.lst` files need to be.

I'm sorry for such a trivial issue, any help would be appreciated.

**Comment by Prologueyan** [comment]
How did u solved this issue?
